### ISSUE TITLE
How to use with asciinema.org ?

### ISSUE THREAD

**Issue by pinage404** [murilo-cunha/slidev-addon-asciinema#11]
Hello,

Thanks for this module

I would like to use it with https://asciinema.org

```vue
<Asciinema src="https://asciinema.org/a/496261.cast" />
```

But it calls a wrong URL `http://localhost:3030/https://asciinema.org/a/496261.cast`

How to use with https://asciinema.org ?

**Comment by murilo-cunha** [comment]
Hi,

Thanks for submitting the issue.

The `src` parameter should point to the file path so we can read the file and render the contents.

The URL path there will actually download the file, so it does not work.

If you want to render something from `asciinema.org`, a more elegant solution would be to embed it as an `iframe`

```html
<iframe src="https://asciinema.org/a/646947/iframe?speed=5" w-full h-105/>
```

(and customize CSS)

Closing this issue since there's a simple workaround for those cases 😊

**Comment by pinage404** [comment]
i was not aware of this solution

Thanks !
